version: '3.7'
services:
  next-app:
    build:
      context: .
      dockerfile: app.dockerfile  # Ensure this matches your Dockerfile name
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production