version: '3.7'
services:
  next-app:
    build:
      context: .
      dockerfile: app.dockerfile  # Specify the correct Dockerfile name
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules