version: "3.7"

services:
  account:
    build:
      context: .
      dockerfile: ./account/app.dockerfile
    depends_on:
      - account_db
    environment:
      DATABASE_URL: postgres://postgres:root@account_db/account_db?sslmode=disable
      SECRET_KEY: e945010e2816a63e76226a74f656b71da545fd9375525b73b7a991e4ff9050b328c8c351bbc11d00980941a804eed8690cdf36a8e94fc93e62c7474da25b4091036eecce162d207d8ec97ef41f9530dfdec17f4144c5a9b233a5c256531e923bc18e5f146815467307da78cc957e23063e0b313a0fd65be93912df761c391de2ca67c3149bda5ba697b81814771d5cf321b21759de70bbb9f8e87c37d90a1ff12d0590be5012bc1eb402773708229ece710abdfd90aff69e8ae7ab88e411c9e7a36a4dc261b9597fdcfa30444e54eb30857667871b8d568b416a998e490bfb804708ddfffade9d85650e59d6585b4e803b340e8accaf7c3d32e278df20bb9e99
    restart: on-failure
    ports:
      - "8080"
      - "2345:2345"  # Expose Delve debug port

  catalog:
    build:
      context: .
      dockerfile: ./catalog/app.dockerfile
    depends_on:
      - catalog_db
    environment:
      DATABASE_URL: http://catalog_db:9200
    restart: on-failure
    ports:
      - "8080"
      - "2346:2345"  # Expose Delve debug port for catalog service

  order:
    build:
      context: .
      dockerfile: ./order/app.dockerfile
    depends_on:
      - order_db
    environment:
      DATABASE_URL: postgres://postgres:root@order_db/order_db?sslmode=disable
      ACCOUNT_SERVICE_URL: account:8080
      CATALOG_SERVICE_URL: catalog:8080
    restart: on-failure
    ports:
      - "8080"
      - "2347:2345"  # Expose Delve debug port for order service

  graphql:
    build:
      context: .
      dockerfile: ./graphql/app.dockerfile
    ports:
      - "8000:8080"
      - "2348:2345" 
    depends_on:
      - account
      - catalog
    environment:
      ACCOUNT_SERVICE_URL: account:8080
      CATALOG_SERVICE_URL: catalog:8080
      ORDER_SERVICE_URL: order:8080
    restart: on-failure
    

  # Database services
  account_db:
    build:
      context: ./account
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5431:5432"
    restart: unless-stopped

  catalog_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"

  order_db:
    build:
      context: ./order
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5430:5432"
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    environment:
      - ELASTICSEARCH_HOSTS=http://catalog_db:9200
    ports:
      - "5601:5601"
